version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: drizzle
      POSTGRES_PASSWORD: drizzle
      POSTGRES_DB: drizzle
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
